spring:
  datasource:
    url: jdbc:h2:~/jpaShop;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver




  jpa:
    hibernate:
      ddl-auto: create  # 요것 덕분에 jpa가 실행될 때 table이 자동 생성됨.

    properties:
      hibernate:
#        show_sql: true
        format_sql: true

    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug